@echo off
echo ========================================
echo Testing Full Document Processing Workflow
echo ========================================

REM Step 1: Create upload request
echo 1. Creating upload request...
curl -X POST "https://j0uu01wdqa.execute-api.us-east-1.amazonaws.com/dev/api/v1/document/upload" ^
  -H "Content-Type: application/json" ^
  -d "{\"patientId\":\"patient-workflow-test\",\"files\":[{\"documentType\":\"medical_record\",\"contentType\":\"application/pdf\",\"size\":1024000}]}" ^
  -o upload_response.json

echo.
echo Upload response saved to upload_response.json
type upload_response.json
echo.

REM Step 2: Extract requestId (manual step for now)
echo 2. Please copy the requestId from above and use it in the next commands
echo.

REM Step 3: Check processing status
echo 3. To check status, run:
echo curl -X GET "https://j0uu01wdqa.execute-api.us-east-1.amazonaws.com/dev/api/v1/document/request/YOUR_REQUEST_ID"
echo.

REM Step 4: Generate discharge summary (after processing completes)
echo 4. To get discharge summary, run:
echo curl -X GET "https://j0uu01wdqa.execute-api.us-east-1.amazonaws.com/dev/api/v1/discharge-summary/patient-workflow-test"
echo.

echo ========================================
echo Workflow Test Complete
echo ========================================
echo.
echo IMPORTANT: The discharge summary will only work after:
echo 1. You upload a document using the presigned URL
echo 2. The document is processed by Textract (OCR)
echo 3. AI summary is generated by Bedrock
echo.
pause